name: Build

on:
  workflow_dispatch:
  push:  
    branches:
      - master

env:
  DOTNET_VERSION: "8.x"    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      # Build Docker Compose services
      - name: Build services
        run: docker compose build